name: Python Scheduled Script

on:
  schedule:
  - cron: "* * * * *"

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Set Timezone
          uses: szenius/set-timezone@v1.0
          with:
            timezoneLinuz: "Europe/Istanbul"
        - name: Checkout repository content
          uses: actions/checkout@v2 # Checkout the repository content to github runner.
        - name: Setup Python Version
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
          - name: Install Python dependencies
            uses: py-actions/py-dependency-install@v2
            with:
              path: "requirements.txt"
          - name: Execute Python script
            run: python weatherstates.py
          - name: Commit files
            run:
              git config --local user.name aksshaya22
              git config --local user.email "aksshayabalaji@gmail.com"
              git add --all
              git commit -am "GH ACTION Headlines $(date)"
              git push origin main
            env:
              REPO_KEY : ${{secrets.GITHUB_TOKEN}}
              username: github-actions
